# Jekyll Defaults
title: Cult of the Mundane
description: Github pages yeah!
baseurl: "" # the subpath of your site, e.g. /blog

url: "https://corejh.github.io/"
github: http://github.com/corejh/
highlighter: rouge
markdown: kramdown
permalink: /post/:title/
paginate: 4
plugins: [jekyll-paginate]
paginate_path: "/page:num"
rss_path: /feed.xml
navigation:
- text: About
  url: /about/
- text: Archives
  url: /archives/
- text: Tags
  url: /tags/
